<?php

    $codeHero = "tutoriales";
    //echo ": $codeHero"."<br>";
    $numero = 21;
    $codeHero = $numero;
    //echo ": $codeHero"."<br>";
    $entero = 10;
    //echo "$entero"."<br>";
    $enteroNegativo = -123;
    //echo "$enteroNegativo"."<br>";
    $coma_flotante = 9345345.3243234;
    //echo "$coma_flotante"."<br>";
    $coma_flotante_menos_preciso = 123.123;
    //echo "$coma_flotante_menos_preciso"."<br>";
    $ejecutar = true;
    //echo "$ejecutar"."<br>";
    $terminar = false;
    //echo "$terminar"."<br>";
    $cadena = "una cadena de caracteres";
    //echo "$cadena"."<br>";
    $cadena2 = 'Otra cadena de caracteres'."<br>";
    //echo "cadena2"."<br>";
    $cadena3 = "Esta cadena contiene 'comillas simples'";
    //echo "$cadena3"."<br>";
    $cadena4 = 'Y esta otra contiene "comillas dobles"';
    //echo "$cadena4"."<br>";
    define('url', 'codehero.co');
    echo url."<br>";
    define('FECHA_CREACION', 2013);
    echo FECHA_CREACION."<br>";